name: Check Upstream Updates and Build

on:
  schedule:
    - cron: '0 * * * *'  # Vérifie chaque heure si l'upstream a changé
  push:
    branches: master

jobs:
  check-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch upstream changes
        run: |
          git remote add upstream https://github.com/Royalphax/credit-agricole-importer.git
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit || true

      - name: Check if there are new commits
        id: check_changes
        run: echo "::set-output name=changes::$(git rev-list HEAD...upstream/main --count)"

      - name: Build and push Docker image if upstream changed
        if: steps.check_changes.outputs.changes != '0'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker build -t kdtheory/credit-agricole-importer .
          docker push kdtheory/credit-agricole-importer
